[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 700
via_ir = true

[profile.ci]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 700
via_ir = true

[profile.ci.fuzz]
runs = 128

[profile.ci.invariant]
runs = 128
depth = 32
fail_on_revert = true

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
override_spacing = false
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"

